server:
  port: 8082

# 需要使用 redis 的话，放开这里
#spring:
#  redis:
#    host: 127.0.0.1
#    database: 0

security:
  oauth2:
    resource:
      filter-order: 3
logging.level.org.springframework.security: DEBUG
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/module/*Mapper.xml
  typeAliasesPackage: moe.cnkirito.security.oauth2.code.modular.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multiple  ResultSetsEnabled: true
